import type { NextPage } from 'next'
import Head from 'next/head'
import HomePage from '../components/HomePage'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Wrises</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HomePage />
      </main>

      <footer>
        {/* The footer of the page goes here */}
      </footer>
    </div>
  )
}

export default HomePage
